---
version: '2'
services:
    rancheros-ansible:
        image: rancheros-ansible 
        build: .
        privileged: true
        ports:
            - "127.0.0.1:5900:5900"        
        command: build /opt/ansible-template/rancheros.json
        volumes: 
            - build:/build
            - /dev/kvm:/dev/kvm:rw
            - /dev/net/tun:/dev/net/tun:rw

volumes:
  build:
