---
version: '2'
services:
    packer-rancheros:
        image: jcpowermac/packer-rancheros 
        privileged: true
        ports:
            - "0.0.0.0:5900:5900"
        command: build -only rancher-scsi-e1000 -var 'device=/dev/sda' /opt/hashicorp/etc/packer/rancheros.json
        #environment:
        #    PACKER_LOG: 1
        volumes: 
            - build:/build
            - /dev/kvm:/dev/kvm:rw
            - /dev/net/tun:/dev/net/tun:rw

volumes:
  build:
