---
- name: Configuration After Build
  hosts: localhost
  gather_facts: true
  tasks:
    - name: packages to install
      yum:
        pkg: "{{ item }}"
        state: latest
      with_items:
        - curl
        - openssh-server
        - ca-certificates

    - name: yum clean all
      command: yum clean all

    - name: write to end of disk
      shell: dd if=/dev/zero of=/EMPTY bs=1M
      ignore_errors: true

    - name: delete EMPTY
      raw: rm -f /EMPTY

    - name: sync filesystem
      command: sync
